name: iBegin
favicon: null
layout_spectrum: 0.73248
typography_spectrum: 0.9379397435113788
title: Acosta Jesus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c8c8c8'
    - '#18403e'
    - '#ffffff'
    - '#377e6a'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
